POST  http://localhost:3000/api/members/signup
Content-Type: application/json

{
    "email": "stano@gmail.com",
    "password": "1234"
}

###

POST http://localhost:3000/api/members/login
Content-Type: application/json

{
    "email": "stano@gmail.com",
    "password": "1234"

}

###

POST http://localhost:3000/api/products/add_product
Content-Type: application/json

{
    
    "name": "Nike Air Jordan",
    "size": 25,
    "price": 2500,
    "description": "Nice Shoe"

}

###
GET http://localhost:3000/api/products/get_products


###

POST http://localhost:3000/api/products/delete_product
Content-Type: application/json

{
    "product_id":"663a59f08013c03bc3aa2428"
}